### PR TITLE
gaff2 production

### PR DESCRIPTION
**Pull request by hainm**
Please do **not** merge yet. Just show my progress. Still need to do more analysis to have more successful ligand building (by antechamber and sander).

Good news: The number of missing_min_pdb is reduced from **738** to **96**.

Please use my branch (gaff2_production) if you want to play around.

### CODE REVIEW

**Comment by hainm** [comment]
Ping @dacase here. I will send you examples of failed runs (either from antechamber or sander) soon.

**Comment by hainm** [comment]
@nwmoriarty do you have a chance to test my branch yet?

**Comment by nwmoriarty** [comment]
@hainm I haven't done anything here because I think we need to discuss a plan with DAC. I spoke a little with him last week. I think a teleconference some time in the near future to focus our efforts.

**Comment by hainm** [comment]
@nwmoriarty yeah, I agree.

**Pull request closed without merging**
